import type { Json } from '@/lib/database.types'
import { SUPABASE_URL } from '@/lib/branding'

type Props = { title: string; type: string; payload: Json }
function object(value: Json): Record<string, Json> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, Json> : {} }
function array(value: Json | undefined): Json[] { return Array.isArray(value) ? value : [] }
function text(value: Json | undefined) { return typeof value === 'string' || typeof value === 'number' ? String(value) : '' }
function number(value: Json | undefined) { return typeof value === 'number' ? value : Number(value || 0) }
function tone(value: Json | undefined) { const result=text(value).toLowerCase(); return ['blue','green','amber','red','violet','teal'].includes(result)?result:'blue' }

export function ProcessedBeraniSection({ title, type, payload }: Props) {
  const data=object(payload)
  if(type==='kpis'){ const items=array(data.items).map(object); return <section className="processed-section panel"><div className="processed-section-head"><div><p className="eyebrow">DATA TEROLAH</p><h2>{title}</h2></div>{text(data.subtitle)?<span>{text(data.subtitle)}</span>:null}</div><div className="processed-kpi-grid">{items.map((item,index)=><article className={`processed-kpi kpi-${tone(item.tone)}`} key={index}><span>{text(item.label)}</span><strong>{text(item.value)}</strong>{text(item.note)?<small>{text(item.note)}</small>:null}{text(item.secondary)?<em>{text(item.secondary)}</em>:null}</article>)}</div></section> }
  if(type==='bar_chart'){ const items=array(data.items).map(object); const max=Math.max(number(data.max),...items.map(i=>number(i.value)),1); const thresholds=object(data.thresholds); const good=number(thresholds.good); const warning=number(thresholds.warning); return <section className="processed-section panel"><div className="processed-section-head"><div><p className="eyebrow">PERBANDINGAN WILAYAH</p><h2>{title}</h2></div><span>{text(data.unit)||'%'}</span></div><div className="processed-bars">{items.map((item,index)=>{const value=number(item.value); const level=value>=good?'good':value>=warning?'warning':'low'; return <div className="processed-bar-row" key={index}><span className="bar-label">{text(item.label)}</span><div className="bar-track"><i className={`bar-fill bar-${level}`} style={{width:`${Math.min(100,(value/max)*100)}%`}}/></div><strong>{new Intl.NumberFormat('id-ID',{maximumFractionDigits:1}).format(value)}{text(data.unit)||'%'}</strong></div>})}</div>{(good||warning)?<div className="bar-legend"><span className="legend-good">≥ {good}%</span><span className="legend-warning">{warning}%–{good-0.1}%</span><span className="legend-low">&lt; {warning}%</span></div>:null}</section> }
  if(type==='stat_grid'){ const items=array(data.items).map(object); const hospitals=array(data.hospitals); return <section className="processed-section panel"><div className="processed-section-head"><div><p className="eyebrow">KAPASITAS LAYANAN</p><h2>{title}</h2></div>{text(data.subtitle)?<span>{text(data.subtitle)}</span>:null}</div><div className="processed-stat-grid">{items.map((item,index)=><article key={index}><span>{text(item.icon)}</span><strong>{text(item.value)}</strong><small>{text(item.label)}</small></article>)}</div>{hospitals.length?<details className="processed-details"><summary>Lihat daftar RS layanan TBC RO ({hospitals.length})</summary><div className="hospital-chip-grid">{hospitals.map((name,index)=><span key={index}>{text(name)}</span>)}</div></details>:null}</section> }
  if(type==='trend'){ const series=array(data.series).map(object); return <section className="processed-section panel"><div className="processed-section-head"><div><p className="eyebrow">TREN INDIKATOR</p><h2>{title}</h2></div></div><div className="trend-grid">{series.map((serie,index)=><article className="trend-card" key={index}><h3>{text(serie.label)}</h3><div className="trend-values">{array(serie.values).map((entry,subIndex)=>{const value=object(entry); return <div key={subIndex}><span>{text(value.period)}</span><strong>{text(value.value)}{text(serie.unit)}</strong></div>})}</div></article>)}</div>{text(data.periodNote)?<p className="processed-note">{text(data.periodNote)}</p>:null}</section> }
  if(type==='facts'){ const items=array(data.items).map(object); return <section className="processed-section panel"><div className="processed-section-head"><div><p className="eyebrow">SOROTAN</p><h2>{title}</h2></div></div><div className="processed-fact-grid">{items.map((item,index)=><article key={index}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{text(item.title)}</h3><p>{text(item.detail)}</p></div></article>)}</div></section> }
  if(type==='text'){ return <section className="processed-section panel document-text-panel"><p className="eyebrow">RINGKASAN DOKUMEN</p><h2>{title}</h2><p>{text(data.text)}</p></section> }
  if(type==='image'){ const path=text(data.path); const url=path?`${SUPABASE_URL}/storage/v1/object/public/berani-documents/${encodeURI(path)}`:''; return <section className="processed-section panel document-image-panel"><p className="eyebrow">PREVIEW VISUAL</p><h2>{title}</h2>{url?<img src={url} alt={text(data.caption)||title} className="processed-image-preview"/>:null}</section> }
  return null
}
