export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[]
type Rel={foreignKeyName:string;columns:string[];isOneToOne:boolean;referencedRelation:string;referencedColumns:string[]}
type Table<Row,Insert=Partial<Row>,Update=Partial<Row>>={Row:Row;Insert:Insert;Update:Update;Relationships:Rel[]}
type Agenda={created_at:string;id:number;kode:string|null;legacy_id:string|null;nama_agenda:string;pic:string|null;status:string;tanggal:string;tipe:string|null;updated_at:string}
type Isu={created_at:string;id:number;kode:string|null;legacy_id:string|null;nama_isu:string;opd_terkait:string|null;prioritas:string|null;ringkasan:string|null;status_monitoring:string;updated_at:string}
type Kunjungan={anggota_tim:string|null;created_at:string;id:number;kode:string|null;legacy_id:string|null;link_notulen:string|null;nama_opd:string;notulen_pdf_name:string|null;notulen_pdf_path:string|null;pejabat:string|null;status:string;tanggal:string;topik:string;updated_at:string}
type Media={created_at:string;id:number;judul_berita:string;kode:string|null;legacy_id:string|null;link_berita:string|null;nama_media:string|null;sentimen:string|null;tanggal:string;updated_at:string}
type Rekomendasi={created_at:string;id:number;judul:string;kode:string|null;legacy_id:string|null;link_doc:string|null;opd_terkait:string|null;pic:string|null;ringkasan:string|null;status:string;updated_at:string}
type Tim={active:boolean;bio:string|null;created_at:string;cv_path:string|null;cv_url:string|null;id:number;kode:string|null;legacy_id:string|null;link_cv:string|null;link_foto:string|null;nama:string;peran:string|null;photo_path:string|null;photo_url:string|null;sort_order:number;updated_at:string}
type DashboardOverview={total_kunjungan:number|null;total_isu:number|null;total_policy_brief:number|null;total_media:number|null;total_agenda:number|null;total_tim:number|null;media_positif:number|null;media_netral:number|null;media_negatif:number|null;isu_tinggi:number|null;isu_sedang:number|null;isu_rendah:number|null}
export type Database={__InternalSupabase:{PostgrestVersion:'14.5'};public:{Tables:{agenda:Table<Agenda,{created_at?:string;id?:number;kode?:string|null;legacy_id?:string|null;nama_agenda:string;pic?:string|null;status?:string;tanggal:string;tipe?:string|null;updated_at?:string},Partial<Agenda>>;isu_strategis:Table<Isu,{created_at?:string;id?:number;kode?:string|null;legacy_id?:string|null;nama_isu:string;opd_terkait?:string|null;prioritas?:string|null;ringkasan?:string|null;status_monitoring?:string;updated_at?:string},Partial<Isu>>;kunjungan:Table<Kunjungan,{anggota_tim?:string|null;created_at?:string;id?:number;kode?:string|null;legacy_id?:string|null;link_notulen?:string|null;nama_opd:string;notulen_pdf_name?:string|null;notulen_pdf_path?:string|null;pejabat?:string|null;status?:string;tanggal:string;topik:string;updated_at?:string},Partial<Kunjungan>>;media_monitoring:Table<Media,{created_at?:string;id?:number;judul_berita:string;kode?:string|null;legacy_id?:string|null;link_berita?:string|null;nama_media?:string|null;sentimen?:string|null;tanggal:string;updated_at?:string},Partial<Media>>;rekomendasi:Table<Rekomendasi,{created_at?:string;id?:number;judul:string;kode?:string|null;legacy_id?:string|null;link_doc?:string|null;opd_terkait?:string|null;pic?:string|null;ringkasan?:string|null;status?:string;updated_at?:string},Partial<Rekomendasi>>;tim_analisis:Table<Tim,{active?:boolean;bio?:string|null;created_at?:string;cv_path?:string|null;cv_url?:string|null;id?:number;kode?:string|null;legacy_id?:string|null;link_cv?:string|null;link_foto?:string|null;nama:string;peran?:string|null;photo_path?:string|null;photo_url?:string|null;sort_order?:number;updated_at?:string},Partial<Tim>>};Views:{dashboard_stats:{Row:{total_agenda:number|null;total_isu:number|null;total_kunjungan:number|null;total_media:number|null;total_policy_brief:number|null};Relationships:[]};dashboard_overview:{Row:DashboardOverview;Relationships:[]}};Functions:{ah_admin_change_pin:{Args:{p_new_pin:string};Returns:boolean};ah_admin_login:{Args:{p_pin:string};Returns:{error_code:string|null;expires_at:string|null;session_token:string|null;success:boolean}[]};ah_admin_logout:{Args:never;Returns:boolean};ah_admin_session_check:{Args:never;Returns:boolean}};Enums:Record<never,never>;CompositeTypes:Record<never,never>}}