'use server'

import { revalidatePath } from 'next/cache'
import { requireActionUser } from '@/lib/auth'
import { driveFileId, TEAM_ASSET_BUCKET } from '@/lib/branding'
import type { Database } from '@/lib/database.types'

type TeamUpdate = Database['public']['Tables']['tim_analisis']['Update']

const MAX_FILE_SIZE = 10 * 1024 * 1024
const IMAGE_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp'])
const CV_TYPES = new Set(['application/pdf'])
const text = (fd: FormData, key: string) => String(fd.get(key) ?? '').trim()
function required(fd:FormData,key:string,label:string,max=5000){const result=text(fd,key);if(!result)throw new Error(`${label} wajib diisi.`);if(result.length>max)throw new Error(`${label} terlalu panjang.`);return result}
function optional(fd:FormData,key:string,label:string,max=5000){const result=text(fd,key);if(result.length>max)throw new Error(`${label} terlalu panjang.`);return result}
function idValue(fd:FormData,key:string,label:string){const result=Number(required(fd,key,label,20));if(!Number.isSafeInteger(result)||result<=0)throw new Error(`${label} tidak valid.`);return result}
function fileFrom(fd:FormData,key:string){const item=fd.get(key);return item instanceof File&&item.size>0?item:null}
function extensionFor(type:string,fallback='bin'){if(type==='image/jpeg')return'jpg';if(type==='image/png')return'png';if(type==='image/webp')return'webp';if(type==='application/pdf')return'pdf';return fallback}
function refresh(){revalidatePath('/pengaturan');revalidatePath('/tim-analisis');revalidatePath('/dashboard')}
async function adminClient(){return(await requireActionUser(['admin'])).supabase}
async function uploadFile(supabase:Awaited<ReturnType<typeof adminClient>>,memberId:number,kind:'photo'|'cv',file:File){const allowed=kind==='photo'?IMAGE_TYPES:CV_TYPES;if(!allowed.has(file.type))throw new Error(kind==='photo'?'Foto harus JPG, PNG, atau WEBP.':'CV harus berupa PDF.');if(file.size>MAX_FILE_SIZE)throw new Error('Ukuran file maksimal 10 MB.');const ext=extensionFor(file.type);const path=`${kind==='photo'?'photos':'cv'}/${memberId}-${Date.now()}.${ext}`;const body=Buffer.from(await file.arrayBuffer());const{error}=await supabase.storage.from(TEAM_ASSET_BUCKET).upload(path,body,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw new Error(`Upload ${kind==='photo'?'foto':'CV'} gagal: ${error.message}`);const{data}=supabase.storage.from(TEAM_ASSET_BUCKET).getPublicUrl(path);return{path,url:data.publicUrl}}

export async function addTeamMember(formData:FormData){const supabase=await adminClient();const{data:last}=await supabase.from('tim_analisis').select('sort_order').order('sort_order',{ascending:false}).limit(1).maybeSingle();const{data:member,error}=await supabase.from('tim_analisis').insert({nama:required(formData,'nama','Nama',300),peran:optional(formData,'peran','Peran',500),bio:optional(formData,'bio','Bio',2000),active:true,sort_order:Number(last?.sort_order||0)+1}).select('id').single();if(error||!member)throw new Error(error?.message||'Gagal menambah anggota.');const updates:TeamUpdate={};const photo=fileFrom(formData,'photo_file');const cv=fileFrom(formData,'cv_file');if(photo){const uploaded=await uploadFile(supabase,member.id,'photo',photo);updates.photo_path=uploaded.path;updates.photo_url=uploaded.url}if(cv){const uploaded=await uploadFile(supabase,member.id,'cv',cv);updates.cv_path=uploaded.path;updates.cv_url=uploaded.url}if(Object.keys(updates).length){const{error:updateError}=await supabase.from('tim_analisis').update(updates).eq('id',member.id);if(updateError)throw new Error(updateError.message)}refresh()}

export async function updateTeamMember(formData:FormData){const supabase=await adminClient();const id=idValue(formData,'id','ID anggota');const updates:TeamUpdate={nama:required(formData,'nama','Nama',300),peran:optional(formData,'peran','Peran',500)||null,bio:optional(formData,'bio','Bio',2000)||null,active:text(formData,'active')==='true',sort_order:Math.max(0,Number(text(formData,'sort_order'))||0)};const photo=fileFrom(formData,'photo_file');const cv=fileFrom(formData,'cv_file');if(photo){const uploaded=await uploadFile(supabase,id,'photo',photo);updates.photo_path=uploaded.path;updates.photo_url=uploaded.url}if(cv){const uploaded=await uploadFile(supabase,id,'cv',cv);updates.cv_path=uploaded.path;updates.cv_url=uploaded.url}const{error}=await supabase.from('tim_analisis').update(updates).eq('id',id);if(error)throw new Error(error.message);refresh()}

async function fetchDriveAsset(url:string,kind:'photo'|'cv'){const id=driveFileId(url);if(!id)throw new Error('ID Google Drive tidak dikenali.');const response=await fetch(`https://drive.usercontent.google.com/download?id=${id}&export=download&confirm=t`,{redirect:'follow',cache:'no-store'});if(!response.ok)throw new Error(`Google Drive merespons ${response.status}.`);if(Number(response.headers.get('content-length')||0)>MAX_FILE_SIZE)throw new Error('File lebih besar dari 10 MB.');const declared=(response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();const mime=kind==='photo'?(IMAGE_TYPES.has(declared)?declared:'image/jpeg'):'application/pdf';const body=Buffer.from(await response.arrayBuffer());if(!body.length||body.length>MAX_FILE_SIZE)throw new Error('File Google Drive kosong atau terlalu besar.');return{body,mime}}

export async function migrateLegacyTeamAssets(){const supabase=await adminClient();const{data:members,error}=await supabase.from('tim_analisis').select('id,nama,link_foto,link_cv,photo_path,cv_path');if(error)throw new Error(error.message);for(const member of members||[]){const patch:TeamUpdate={};if(!member.photo_path&&member.link_foto){try{const asset=await fetchDriveAsset(member.link_foto,'photo');const path=`photos/${member.id}-legacy.${extensionFor(asset.mime,'jpg')}`;const upload=await supabase.storage.from(TEAM_ASSET_BUCKET).upload(path,asset.body,{contentType:asset.mime,cacheControl:'86400',upsert:true});if(upload.error)throw upload.error;const{data}=supabase.storage.from(TEAM_ASSET_BUCKET).getPublicUrl(path);patch.photo_path=path;patch.photo_url=data.publicUrl}catch(assetError){console.warn(`Migrasi foto ${member.nama} dilewati:`,assetError)}}if(!member.cv_path&&member.link_cv){try{const asset=await fetchDriveAsset(member.link_cv,'cv');const path=`cv/${member.id}-legacy.pdf`;const upload=await supabase.storage.from(TEAM_ASSET_BUCKET).upload(path,asset.body,{contentType:'application/pdf',cacheControl:'3600',upsert:true});if(upload.error)throw upload.error;const{data}=supabase.storage.from(TEAM_ASSET_BUCKET).getPublicUrl(path);patch.cv_path=path;patch.cv_url=data.publicUrl}catch(assetError){console.warn(`Migrasi CV ${member.nama} dilewati:`,assetError)}}if(Object.keys(patch).length){const{error:patchError}=await supabase.from('tim_analisis').update(patch).eq('id',member.id);if(patchError)console.warn(`Update aset ${member.nama} gagal:`,patchError.message)}}refresh()}
