
with seeded(source_key,tanggal,nama_opd,pejabat,topik,tanggal_sumber,notulen_pdf_name,notulen_text) as (values
('sept-2026-bkd','2026-09-02'::date,'Badan Kepegawaian Daerah (BKD) Provinsi Sulawesi Tengah','Dr. Hj. Sitti Asma Ul Husnasyah, S.E., M.M., M.Si. beserta jajaran','Digitalisasi birokrasi, B-KIN, sistem merit, manajemen talenta, dan penguatan integritas ASN','Dokumen sumber mencantumkan Senin, 3 Agustus 2026','NOTULENSI AUDIENSI BKD Sulteng.pdf','Audiensi membahas implementasi 9 Berani khususnya Berani Berintegritas, transformasi digital BKD, B-KIN untuk absensi dan laporan kinerja, I-MUT, merit system, manajemen talenta, serta efisiensi layanan administrasi. Notulensi mencatat 770 profil ASN telah masuk dalam blok manajemen talenta dan BKD memperoleh Nilai A pada evaluasi SAKIB.'),
('sept-2026-pendidikan','2026-09-04'::date,'Dinas Pendidikan Provinsi Sulawesi Tengah','Firmanza DP (Kepala Dinas Pendidikan Provinsi Sulawesi Tengah)','Evaluasi BERANI Cerdas, jangkauan pendidikan pelosok, beasiswa, verifikasi data, dan tujuh jalur program pendidikan',null,'NOTULENSI AUDIENSI DINAS PENDIDIKAN.pdf','Pertemuan membahas jangkauan Berani Cerdas ke wilayah pelosok, strategi jemput bola Anak Tidak Sekolah dan pendaftaran beasiswa, keterbatasan admin layanan, verifikasi data perguruan tinggi, serta tujuh jalur utama Berani Cerdas. Notulensi juga mencatat temuan duplikasi data penerima beasiswa yang memerlukan tindak lanjut dan verifikasi.'),
('sept-2026-dinsos','2026-09-07'::date,'Dinas Sosial Provinsi Sulawesi Tengah','Kiki Rezky Ramdainasari, S.STP, M.M. (Sekretaris Dinas Sosial)','Pemutakhiran DTSEN, digitalisasi data, inovasi INDEP/IDI, dan pengentasan kemiskinan',null,'NOTULENSI AUDIENSI DINSOS SULTENG.pdf','Dinas Sosial memaparkan pengelolaan DTSEN, pemutakhiran data untuk intervensi kemiskinan, empat lokasi prioritas, kolaborasi dengan BPS, serta inovasi INDEP/IDI. Fokus penanganan diarahkan dari kemiskinan ekstrem, miskin reguler, hingga graduasi kemiskinan.'),
('sept-2026-bpbd','2026-09-09'::date,'Badan Penanggulangan Bencana Daerah (BPBD) Provinsi Sulawesi Tengah','Ir. Asbudianto, S.T., M.Si. (Kepala BPBD Provinsi Sulawesi Tengah)','Kesiapsiagaan bencana, SIGANA, integrasi Command Center, sistem logistik, dan sarana prasarana',null,'NOTULENSI AUDIENSI Tim Analisis bersama BPBD.pdf','Pertemuan membahas website pemantauan awal bencana, aplikasi SIGANA untuk laporan masyarakat dengan foto, rencana Sistem Informasi Logistik, integrasi data dengan Command Center, kesiapan 38 personel TRC, tiga posko utama, serta tantangan perawatan alat berat dan perahu speed.'),
('sept-2026-brida','2026-09-11'::date,'Badan Riset dan Inovasi Daerah (BRIDA) Provinsi Sulawesi Tengah','Kepala BRIDA Provinsi Sulawesi Tengah beserta jajaran','Riset dan inovasi daerah, BRIDA Menyapa OPD, IDSD, IGA, dan penguatan kebijakan berbasis riset',null,'NOTULENSI AUDIENSI TIM BERSAMA BRIDA.pdf','BRIDA memaparkan lomba Policy Brief dan Policy Paper, konsep BRIDA Menyapa OPD untuk menjembatani riset dengan kebutuhan lapangan, penguatan IDSD, inovasi daerah, kolaborasi dengan BRIN, serta isu sektor pertanian yang memerlukan tindak lanjut berbasis riset.'),
('sept-2026-bpkad','2026-09-14'::date,'Badan Pengelolaan Keuangan dan Aset Daerah (BPKAD) Provinsi Sulawesi Tengah','Pimpinan/Pejabat BPKAD Provinsi Sulawesi Tengah','Pengelolaan keuangan daerah, Dana Bagi Hasil (DBH), kurang bayar DBH, dan transparansi data fiskal','Dokumen sumber mencantumkan Rabu, 12 Agustus 2026','NOTULENSI HASIL WAWANCARA BPKAD SULTENG.pdf','Wawancara berfokus pada mekanisme perhitungan DBH, transparansi data produksi, kurang bayar DBH, realisasi penyaluran, serta upaya Pemprov berkoordinasi dan melakukan advokasi di tingkat pusat. Notulensi menyebut nilai kurang bayar sekitar Rp523 miliar dan realisasi sekitar Rp13 miliar, yang perlu diperlakukan sebagai data sumber wawancara.'),
('sept-2026-kesbangpol','2026-09-16'::date,'Badan Kesatuan Bangsa dan Politik (Kesbangpol) Provinsi Sulawesi Tengah','Kepala Badan Kesbangpol Provinsi Sulawesi Tengah','Stabilitas politik, demokrasi, ormas, kewaspadaan dini, SILATMAS, Berani Kawal, dan PADI',null,'NOTULENSI KESBANGPOL.pdf','Pertemuan membahas penguatan IDI, pengawasan ormas dan FKUB, aplikasi SILATMAS, Berani Kawal dan PADI, wawasan kebangsaan, pencegahan radikalisme, kewaspadaan dini, serta peran Kesbangpol dalam memantau dinamika sosial-politik dan konflik.'),
('sept-2026-disbunak','2026-09-18'::date,'Dinas Perkebunan dan Peternakan Provinsi Sulawesi Tengah','Kepala Dinas Perkebunan dan Peternakan Provinsi Sulawesi Tengah beserta jajaran','Digitalisasi data, Sibunak, BERANI Makmur, bantuan perkebunan/peternakan, Pokir, dan realisasi program',null,'Notulensi_Disbunak_Sulteng.pdf','Notulensi membahas pembenahan data, dashboard Sibunak, pencatatan bantuan by name/by group berbasis NIK, integrasi dengan Berani Sampora, BERANI Makmur, 47 item Pokir, usulan bantuan perdesaan Rp15 miliar, serta 85 alsintan yang dialokasikan untuk Banggai Kepulauan.'),
('sept-2026-bpsdm','2026-09-21'::date,'Badan Pengembangan Sumber Daya Manusia (BPSDM) Provinsi Sulawesi Tengah','Kepala BPSDM Provinsi Sulawesi Tengah beserta jajaran','Pengembangan kompetensi ASN, e-learning anti korupsi, ASN Belajar, LMS, sistem merit, dan manajemen talenta',null,'notulensi_pertemuan_bpsdm.pdf','BPSDM memaparkan e-learning anti korupsi, program ASN Belajar setiap Jumat, pelatihan kepemimpinan, LMS, akreditasi A untuk diklat pengadaan barang/jasa, integrasi data dengan BKD, sistem merit, asesmen, serta tantangan pemanfaatan sarana asrama.'),
('sept-2026-perpus','2026-09-24'::date,'Dinas Perpustakaan dan Kearsipan Daerah Provinsi Sulawesi Tengah','Pimpinan Dinas Perpustakaan dan Kearsipan Provinsi Sulawesi Tengah beserta jajaran','Literasi digital, IPUSSULTENG, Soraja, digitalisasi aset barcode, Bunda Literasi, dan pelestarian arsip',null,'Notulensi_Pertemuan_Dinas_Perpustakaan_dan_Kearsipan_Sulteng.pdf','Pertemuan membahas capaian perpustakaan digital, tingkat kegemaran membaca, IPUSSULTENG, aplikasi arsip Soraja, rencana arsip aset berbasis barcode, tantangan pustakawan dan anggaran, pengelolaan naskah kuno, serta pengembangan Bunda Literasi dan aplikasi mandiri.')
)
insert into public.kunjungan(source_key,tanggal,nama_opd,pejabat,anggota_tim,topik,status,tanggal_estimasi,tanggal_sumber,notulen_pdf_name,notulen_text)
select source_key,tanggal,nama_opd,pejabat,'Tim Analisis Strategis',topik,'Selesai',true,tanggal_sumber,notulen_pdf_name,notulen_text from seeded
on conflict(source_key) where source_key is not null do update set
tanggal=excluded.tanggal,nama_opd=excluded.nama_opd,pejabat=excluded.pejabat,anggota_tim=excluded.anggota_tim,topik=excluded.topik,status='Selesai',tanggal_estimasi=true,tanggal_sumber=excluded.tanggal_sumber,notulen_pdf_name=excluded.notulen_pdf_name,notulen_text=excluded.notulen_text;

with refs(source_key,opd_name,title,program_label,detail,key_facts,status,reference_urls,source_label,sort_order) as (values
('ref-diskominfo-berdering','DISKOMINFOSANTIK','Berani Berdering — Konektivitas 150 Desa Blankspot','Berani Berdering','Program konektivitas untuk wilayah blankspot melalui dukungan jaringan berbasis satelit termasuk Starlink.','Pagu Rp10,3 miliar; sasaran 150 desa terpencil dan 10 sekolah terpencil; alokasi Rp69 juta per desa; satu jaringan utama dipancarkan ke tiga titik akses.','Siap Dibagikan','["https://sulteng.antaranews.com/berita/390829/sulteng-alokasikan-anggaran-rp103-miliar-untuk-pemerataan-internet","https://sultengprov.go.id/umum/diskominfosantik-sulteng-matangkan-berani-berdering-sinergi-jadi-kunci-sukses-internet-desa/"]'::jsonb,'Dokumen Informasi & Referensi Konten Pemprov Sulteng 2026',10),
('ref-dinsos-dtsen','Dinas Sosial Provinsi Sulawesi Tengah','Pemutakhiran DTSEN melalui IDI / BERANI BERSINAR','BERANI BERSINAR','Pemutakhiran Data Tunggal Sosial Ekonomi Nasional menggunakan wawancara mendalam untuk menggali akar masalah kemiskinan dan kerentanan sosial.','Dilaksanakan di Kota Palu, Donggala, Parigi Moutong, dan Morowali; melibatkan Dinsos, Bappeda, PMD, Dukcapil, Inspektorat, dan BPS.','Siap Dibagikan','[]'::jsonb,'Dokumen Informasi & Referensi Konten + Notulensi Dinsos',20),
('ref-bappeda-mombangu','Bappeda Provinsi Sulawesi Tengah','Pilot Project Fasilitator BERANI MOMBANGU','BERANI MOMBANGU','Program pemberdayaan masyarakat dan percepatan pengentasan kemiskinan serta penurunan stunting melalui fasilitator di desa.','Dokumen sumber menyebut program sebagai pilot project untuk pengentasan kemiskinan di Sulawesi Tengah.','Perlu Verifikasi','[]'::jsonb,'Dokumen Informasi & Referensi Konten Pemprov Sulteng 2026',30),
('ref-perpus-ipussulteng','Dinas Perpustakaan dan Kearsipan Daerah Provinsi Sulawesi Tengah','IPUSSULTENG dan transformasi perpustakaan digital','IPUSSULTENG','Layanan perpustakaan digital Sulawesi Tengah yang bekerja sama dengan IPUSNAS, disertai penguatan sistem kearsipan digital.','Notulensi mencatat peringkat kedua nasional perpustakaan digital dua tahun berturut-turut, tingkat kegemaran membaca peringkat ke-7 nasional, serta Soraja yang telah didaftarkan ke Kemendagri.','Siap Dibagikan','[]'::jsonb,'Dokumen Informasi & Referensi Konten + Notulensi Perpustakaan',40),
('ref-bpbd-sigana','Badan Penanggulangan Bencana Daerah (BPBD) Provinsi Sulawesi Tengah','SIGANA — pelaporan kejadian bencana oleh masyarakat','SIGANA','Aplikasi tanggap bencana yang memungkinkan masyarakat mengirim laporan dan foto kejadian untuk mendukung respons BPBD.','Notulensi juga mencatat integrasi data kebencanaan dengan Command Center dan rencana Sistem Informasi Logistik.','Siap Dibagikan','[]'::jsonb,'Dokumen Informasi & Referensi Konten + Notulensi BPBD',50),
('ref-bkd-bkin','Badan Kepegawaian Daerah (BKD) Provinsi Sulawesi Tengah','B-KIN untuk absensi dan kinerja ASN','B-KIN / Berani Berkinerja','Aplikasi untuk absensi elektronik real-time, laporan kinerja harian, dan penguatan disiplin berbasis data.','Notulensi menyebut B-KIN digunakan sejak 2025 dan manajemen talenta telah memuat 770 profil ASN.','Siap Dibagikan','[]'::jsonb,'Notulensi Audiensi BKD',60),
('ref-bkd-imut','Badan Kepegawaian Daerah (BKD) Provinsi Sulawesi Tengah','I-MUT dan manajemen talenta ASN','I-MUT / Berani Berintegritas','Penguatan integritas mutasi dan seleksi jabatan berbasis kompetensi melalui sistem merit dan manajemen talenta.','Administrasi yang lebih minim kontak langsung ditujukan untuk mempersempit ruang pungli/percaloan; angka dan klaim publik tetap perlu diverifikasi sebelum dibagikan keluar.','Perlu Verifikasi','[]'::jsonb,'Notulensi Audiensi BKD',61),
('ref-pendidikan-berani-cerdas','Dinas Pendidikan Provinsi Sulawesi Tengah','Jemput bola BERANI Cerdas untuk wilayah pelosok','BERANI Cerdas','Tim lapangan mencari Anak Tidak Sekolah sekaligus membantu sosialisasi dan pendaftaran beasiswa bagi masyarakat di wilayah dengan keterbatasan akses.','Notulensi menyebut tujuh jalur utama BERANI Cerdas, termasuk sekolah menengah gratis, beasiswa S1, dokter/calon dokter, S2/S3, dokter spesialis, dan peningkatan kompetensi guru.','Siap Dibagikan','[]'::jsonb,'Notulensi Audiensi Dinas Pendidikan',70),
('ref-brida-menyapa','Badan Riset dan Inovasi Daerah (BRIDA) Provinsi Sulawesi Tengah','BRIDA Menyapa OPD — menjembatani riset dan kebutuhan lapangan','BRIDA Menyapa OPD','Inisiatif untuk mempertemukan hasil riset dengan kebutuhan OPD dan praktik di lapangan.','Contoh dalam notulensi: temuan riset pakan ternak Untad ditindaklanjuti melalui fasilitasi kerja sama dengan Dinas Peternakan dan peneliti.','Siap Dibagikan','[]'::jsonb,'Notulensi Audiensi BRIDA',80),
('ref-brida-lomba','Badan Riset dan Inovasi Daerah (BRIDA) Provinsi Sulawesi Tengah','Lomba Policy Brief dan Policy Paper untuk ASN','Lomba Inovasi Kebijakan','Kompetisi penulisan untuk mendorong ide pembangunan dari ASN dan memperluas budaya kebijakan berbasis tulisan.','Notulensi mencatat target awal 10 pendaftar dan realisasi 78 pendaftar.','Perlu Verifikasi','[]'::jsonb,'Notulensi Audiensi BRIDA',81),
('ref-bpsdm-elearning','Badan Pengembangan Sumber Daya Manusia (BPSDM) Provinsi Sulawesi Tengah','E-learning anti korupsi dan ASN Belajar','E-Learning / ASN Belajar','Sistem pembelajaran mandiri dengan modul, evaluasi, sertifikasi, serta agenda ASN Belajar setiap Jumat.','Notulensi menyebut fasilitas e-learning anti korupsi mampu menampung sekitar 200 peserta dan BPSDM memiliki Akreditasi A untuk diklat pengadaan barang/jasa.','Siap Dibagikan','[]'::jsonb,'Notulensi Pertemuan BPSDM',90),
('ref-kesbangpol-silatmas','Badan Kesatuan Bangsa dan Politik (Kesbangpol) Provinsi Sulawesi Tengah','SILATMAS, Berani Kawal dan PADI','SILATMAS / Berani Kawal / PADI','Digitalisasi pendataan organisasi kemasyarakatan dan pusat data untuk mendukung transparansi serta kewaspadaan daerah.','Kesbangpol juga menjalankan pemantauan dini dinamika politik, ormas, dan potensi konflik sosial.','Siap Dibagikan','[]'::jsonb,'Notulensi Kesbangpol',100),
('ref-disbunak-sibunak','Dinas Perkebunan dan Peternakan Provinsi Sulawesi Tengah','Sibunak dan transparansi bantuan berbasis NIK','Sibunak / BERANI Makmur','Dashboard data sektor perkebunan dan peternakan dengan pencatatan bantuan by name, by group, dan berbasis NIK.','Notulensi menyebut bantuan perkebunan dicatat hingga lokasi/jumlah bibit serta 85 alsintan dialokasikan untuk Banggai Kepulauan.','Siap Dibagikan','[]'::jsonb,'Notulensi Disbunak',110),
('ref-disbunak-bantuan','Dinas Perkebunan dan Peternakan Provinsi Sulawesi Tengah','Bantuan perdesaan dan pengawalan sasaran BERANI Makmur','BERANI Makmur','Penyaluran bantuan diarahkan berdasarkan pemeriksaan desa agar tidak tumpang tindih dengan program yang sudah diterima.','Notulensi mencatat usulan langsung Rp15 miliar dan 47 item kegiatan Pokir; realisasi per September disebut 31%.','Perlu Verifikasi','[]'::jsonb,'Notulensi Disbunak',111),
('ref-bpkad-dbh','Badan Pengelolaan Keuangan dan Aset Daerah (BPKAD) Provinsi Sulawesi Tengah','Transparansi kurang bayar Dana Bagi Hasil','DBH','Bahan penjelasan mengenai perbedaan penetapan hak kurang bayar DBH dengan realisasi penyaluran dari pemerintah pusat.','Notulensi menyebut sekitar Rp523 miliar ditetapkan sebagai kurang bayar dan sekitar Rp13 miliar telah direalisasikan; angka ini perlu diverifikasi sebelum dibagikan keluar.','Perlu Verifikasi','[]'::jsonb,'Notulensi Wawancara BPKAD',120)
)
insert into public.content_references(source_key,opd_name,title,program_label,detail,key_facts,status,reference_urls,source_label,sort_order)
select source_key,opd_name,title,program_label,detail,key_facts,status,reference_urls,source_label,sort_order from refs
on conflict(source_key) do update set
opd_name=excluded.opd_name,title=excluded.title,program_label=excluded.program_label,detail=excluded.detail,key_facts=excluded.key_facts,status=excluded.status,reference_urls=excluded.reference_urls,source_label=excluded.source_label,sort_order=excluded.sort_order,updated_at=now();
