
alter table public.kunjungan
  add column if not exists tanggal_estimasi boolean not null default false,
  add column if not exists tanggal_sumber text,
  add column if not exists notulen_text text,
  add column if not exists source_key text;
create unique index if not exists kunjungan_source_key_uidx on public.kunjungan(source_key) where source_key is not null;

create table if not exists public.berani_update_documents (
  id bigint generated by default as identity primary key,
  update_id bigint not null references public.berani_updates(id) on delete cascade,
  file_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  sheet_name text,
  columns jsonb not null default '[]'::jsonb,
  row_count integer not null default 0 check (row_count >= 0),
  extracted_text text,
  created_at timestamptz not null default now()
);
create index if not exists berani_update_documents_update_idx on public.berani_update_documents(update_id, created_at);

create table if not exists public.berani_document_rows (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.berani_update_documents(id) on delete cascade,
  row_index integer not null check (row_index > 0),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(document_id,row_index)
);
create index if not exists berani_document_rows_document_idx on public.berani_document_rows(document_id,row_index);

create table if not exists public.opd_finding_documents (
  id bigint generated by default as identity primary key,
  finding_id bigint not null references public.opd_findings(id) on delete cascade,
  file_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  extracted_text text,
  created_at timestamptz not null default now()
);
create index if not exists opd_finding_documents_finding_idx on public.opd_finding_documents(finding_id,created_at);

create table if not exists public.content_references (
  id bigint generated by default as identity primary key,
  opd_name text not null,
  title text not null,
  program_label text,
  detail text,
  key_facts text,
  status text not null default 'Draft' check(status in ('Draft','Perlu Verifikasi','Siap Dibagikan')),
  berani_program_id bigint references public.berani_programs(id) on delete set null,
  reference_urls jsonb not null default '[]'::jsonb,
  source_label text,
  source_key text unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists content_references_opd_idx on public.content_references(opd_name,sort_order,id);
create index if not exists content_references_status_idx on public.content_references(status);

drop trigger if exists content_references_set_updated_at on public.content_references;
create trigger content_references_set_updated_at before update on public.content_references
for each row execute function public.set_updated_at();

alter table public.berani_update_documents enable row level security;
alter table public.berani_document_rows enable row level security;
alter table public.opd_finding_documents enable row level security;
alter table public.content_references enable row level security;

grant select,insert,update,delete on public.berani_update_documents to anon;
grant select,insert,update,delete on public.berani_document_rows to anon;
grant select,insert,update,delete on public.opd_finding_documents to anon;
grant select,insert,update,delete on public.content_references to anon;
grant usage,select on all sequences in schema public to anon;

drop policy if exists public_read on public.berani_update_documents;
create policy public_read on public.berani_update_documents for select to anon using(true);
drop policy if exists public_insert on public.berani_update_documents;
create policy public_insert on public.berani_update_documents for insert to anon with check(true);
drop policy if exists public_update on public.berani_update_documents;
create policy public_update on public.berani_update_documents for update to anon using(true) with check(true);
drop policy if exists public_delete on public.berani_update_documents;
create policy public_delete on public.berani_update_documents for delete to anon using(true);

drop policy if exists public_read on public.berani_document_rows;
create policy public_read on public.berani_document_rows for select to anon using(true);
drop policy if exists public_insert on public.berani_document_rows;
create policy public_insert on public.berani_document_rows for insert to anon with check(true);
drop policy if exists public_update on public.berani_document_rows;
create policy public_update on public.berani_document_rows for update to anon using(true) with check(true);
drop policy if exists public_delete on public.berani_document_rows;
create policy public_delete on public.berani_document_rows for delete to anon using(true);

drop policy if exists public_read on public.opd_finding_documents;
create policy public_read on public.opd_finding_documents for select to anon using(true);
drop policy if exists public_insert on public.opd_finding_documents;
create policy public_insert on public.opd_finding_documents for insert to anon with check(true);
drop policy if exists public_update on public.opd_finding_documents;
create policy public_update on public.opd_finding_documents for update to anon using(true) with check(true);
drop policy if exists public_delete on public.opd_finding_documents;
create policy public_delete on public.opd_finding_documents for delete to anon using(true);

drop policy if exists public_read on public.content_references;
create policy public_read on public.content_references for select to anon using(true);
drop policy if exists public_insert on public.content_references;
create policy public_insert on public.content_references for insert to anon with check(true);
drop policy if exists public_update on public.content_references;
create policy public_update on public.content_references for update to anon using(true) with check(true);
drop policy if exists public_delete on public.content_references;
create policy public_delete on public.content_references for delete to anon using(true);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
 'finding-documents','finding-documents',true,15728640,
 array[
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/msword'
 ]::text[]
)
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists ah_finding_documents_select on storage.objects;
create policy ah_finding_documents_select on storage.objects for select to anon using(bucket_id='finding-documents');
drop policy if exists ah_finding_documents_insert on storage.objects;
create policy ah_finding_documents_insert on storage.objects for insert to anon
with check(bucket_id='finding-documents' and lower(storage.extension(name)) in ('pdf','xlsx','xls','docx','doc'));
drop policy if exists ah_finding_documents_delete on storage.objects;
create policy ah_finding_documents_delete on storage.objects for delete to anon using(bucket_id='finding-documents');

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='content_references'
  ) then
    alter publication supabase_realtime add table public.content_references;
  end if;
end $$;
