create table if not exists public.kunjungan_documents (
  id bigint generated by default as identity primary key,
  kunjungan_id bigint not null references public.kunjungan(id) on delete cascade,
  title text not null default 'Notulensi',
  file_path text not null,
  file_name text not null,
  mime_type text not null default 'application/pdf',
  created_at timestamptz not null default now()
);
create index if not exists kunjungan_documents_kunjungan_id_idx on public.kunjungan_documents(kunjungan_id, created_at desc);

create table if not exists public.berani_programs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  summary text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.berani_updates (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.berani_programs(id) on delete cascade,
  title text not null,
  opd_name text,
  period_label text,
  summary text,
  source_key text unique,
  file_path text,
  file_name text,
  mime_type text,
  file_size bigint,
  sheet_name text,
  columns jsonb not null default '[]'::jsonb,
  row_count integer not null default 0 check (row_count >= 0),
  extracted_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists berani_updates_program_created_idx on public.berani_updates(program_id, created_at desc);
create index if not exists berani_updates_opd_idx on public.berani_updates(opd_name);

create table if not exists public.berani_update_rows (
  id bigint generated by default as identity primary key,
  update_id bigint not null references public.berani_updates(id) on delete cascade,
  row_index integer not null check (row_index > 0),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(update_id, row_index)
);
create index if not exists berani_update_rows_update_idx on public.berani_update_rows(update_id, row_index);

create table if not exists public.opd_findings (
  id bigint generated by default as identity primary key,
  opd_name text not null,
  title text not null,
  detail text,
  category text not null default 'Temuan'
    check (category in ('Temuan','Positif','Perlu Perhatian','Potensi','Tindak Lanjut')),
  finding_date date not null default current_date,
  berani_program_id bigint references public.berani_programs(id) on delete set null,
  source_label text,
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists opd_findings_opd_date_idx on public.opd_findings(opd_name, finding_date desc);
create index if not exists opd_findings_berani_idx on public.opd_findings(berani_program_id);

drop trigger if exists berani_programs_set_updated_at on public.berani_programs;
create trigger berani_programs_set_updated_at before update on public.berani_programs
for each row execute function public.set_updated_at();

drop trigger if exists berani_updates_set_updated_at on public.berani_updates;
create trigger berani_updates_set_updated_at before update on public.berani_updates
for each row execute function public.set_updated_at();

drop trigger if exists opd_findings_set_updated_at on public.opd_findings;
create trigger opd_findings_set_updated_at before update on public.opd_findings
for each row execute function public.set_updated_at();

alter table public.kunjungan_documents enable row level security;
alter table public.berani_programs enable row level security;
alter table public.berani_updates enable row level security;
alter table public.berani_update_rows enable row level security;
alter table public.opd_findings enable row level security;

grant select, insert, update, delete on public.kunjungan_documents to anon;
grant select on public.berani_programs to anon;
grant select, insert, update, delete on public.berani_updates to anon;
grant select, insert, update, delete on public.berani_update_rows to anon;
grant select, insert, update, delete on public.opd_findings to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists public_read on public.kunjungan_documents;
create policy public_read on public.kunjungan_documents for select to anon using (true);
drop policy if exists public_insert on public.kunjungan_documents;
create policy public_insert on public.kunjungan_documents for insert to anon with check (true);
drop policy if exists public_update on public.kunjungan_documents;
create policy public_update on public.kunjungan_documents for update to anon using (true) with check (true);
drop policy if exists public_delete on public.kunjungan_documents;
create policy public_delete on public.kunjungan_documents for delete to anon using (true);

drop policy if exists public_read on public.berani_programs;
create policy public_read on public.berani_programs for select to anon using (active = true);

drop policy if exists public_read on public.berani_updates;
create policy public_read on public.berani_updates for select to anon using (true);
drop policy if exists public_insert on public.berani_updates;
create policy public_insert on public.berani_updates for insert to anon with check (true);
drop policy if exists public_update on public.berani_updates;
create policy public_update on public.berani_updates for update to anon using (true) with check (true);
drop policy if exists public_delete on public.berani_updates;
create policy public_delete on public.berani_updates for delete to anon using (true);

drop policy if exists public_read on public.berani_update_rows;
create policy public_read on public.berani_update_rows for select to anon using (true);
drop policy if exists public_insert on public.berani_update_rows;
create policy public_insert on public.berani_update_rows for insert to anon with check (true);
drop policy if exists public_update on public.berani_update_rows;
create policy public_update on public.berani_update_rows for update to anon using (true) with check (true);
drop policy if exists public_delete on public.berani_update_rows;
create policy public_delete on public.berani_update_rows for delete to anon using (true);

drop policy if exists public_read on public.opd_findings;
create policy public_read on public.opd_findings for select to anon using (true);
drop policy if exists public_insert on public.opd_findings;
create policy public_insert on public.opd_findings for insert to anon with check (true);
drop policy if exists public_update on public.opd_findings;
create policy public_update on public.opd_findings for update to anon using (true) with check (true);
drop policy if exists public_delete on public.opd_findings;
create policy public_delete on public.opd_findings for delete to anon using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'berani-documents',
  'berani-documents',
  true,
  15728640,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists ah_berani_documents_select on storage.objects;
create policy ah_berani_documents_select
on storage.objects for select to anon
using (bucket_id = 'berani-documents');

drop policy if exists ah_berani_documents_insert on storage.objects;
create policy ah_berani_documents_insert
on storage.objects for insert to anon
with check (
  bucket_id = 'berani-documents'
  and lower(storage.extension(name)) in ('pdf','xlsx','xls','docx','doc')
);

drop policy if exists ah_berani_documents_delete on storage.objects;
create policy ah_berani_documents_delete
on storage.objects for delete to anon
using (bucket_id = 'berani-documents');

drop policy if exists ah_kunjungan_notulensi_delete on storage.objects;
create policy ah_kunjungan_notulensi_delete
on storage.objects for delete to anon
using (bucket_id = 'kunjungan-notulensi');

insert into public.berani_programs(slug,name,summary,sort_order) values
('berani-cerdas','BERANI Cerdas','Pusat data dan pembaruan terkait program BERANI Cerdas.',1),
('berani-sehat','BERANI Sehat','Pusat data dan pembaruan terkait program BERANI Sehat.',2),
('berani-lancar','BERANI Lancar','Pusat data dan pembaruan terkait infrastruktur dan konektivitas BERANI Lancar.',3),
('berani-menyala','BERANI Menyala','Pusat data dan pembaruan terkait program BERANI Menyala.',4),
('berani-berdering','BERANI Berdering','Pusat data dan pembaruan terkait program BERANI Berdering.',5),
('berani-tangkap','BERANI Tangkap','Pusat data dan pembaruan terkait program BERANI Tangkap.',6),
('berani-panen-raya','BERANI Panen Raya','Pusat data dan pembaruan terkait program BERANI Panen Raya.',7),
('berani-berintegritas','BERANI Berintegritas','Pusat data dan pembaruan terkait program BERANI Berintegritas.',8),
('berani-berkah','BERANI Berkah','Pusat data dan pembaruan terkait program BERANI Berkah.',9)
on conflict (slug) do update set
  name = excluded.name,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  active = true;
