create table if not exists public.feature_notes (
  id bigint generated by default as identity primary key,
  feature_key text not null,
  entity_key text not null default '__module__',
  title text,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feature_notes_feature_key_check check (feature_key ~ '^[a-z0-9_-]{2,80}$'),
  constraint feature_notes_entity_key_check check (length(entity_key) between 1 and 180),
  constraint feature_notes_title_check check (title is null or length(title) <= 300),
  constraint feature_notes_content_check check (length(content) between 1 and 12000)
);

create index if not exists feature_notes_scope_idx
  on public.feature_notes(feature_key, entity_key, updated_at desc);

alter table public.feature_notes enable row level security;

drop policy if exists public_read on public.feature_notes;
create policy public_read on public.feature_notes
for select to anon
using (true);

drop policy if exists public_insert on public.feature_notes;
create policy public_insert on public.feature_notes
for insert to anon
with check (public.ah_admin_session_check());

drop policy if exists public_update on public.feature_notes;
create policy public_update on public.feature_notes
for update to anon
using (public.ah_admin_session_check())
with check (public.ah_admin_session_check());

drop policy if exists public_delete on public.feature_notes;
create policy public_delete on public.feature_notes
for delete to anon
using (public.ah_admin_session_check());
