delete from public.content_references where source_key like 'ref-%';
insert into public.content_references(source_key,opd_name,title,program_label,detail,key_facts,status,reference_urls,source_label,sort_order)
values
('official-content-2026-diskominfo','DISKOMINFOSANTIK','Berani Berdering - konektivitas desa blankspot','Berani Berdering','Program bantuan jaringan berbasis satelit, termasuk Starlink, untuk menghapus wilayah blankspot dan mempercepat transformasi digital di wilayah pedesaan.','Pagu Rp10,3 miliar; sasaran 150 desa terpencil dan 10 sekolah terpencil; alokasi Rp69 juta per desa. Sekitar Rp40 juta untuk infrastruktur/peralatan dan sekitar Rp29 juta untuk jaringan satelit serta penguatan SDM. Satu jaringan utama dipancarkan ke 3 titik akses. Sigi dan Tojo Una-Una masing-masing mendapat 15 desa; kabupaten lain masing-masing 12 desa.','Siap Dibagikan','["https://sulteng.antaranews.com/berita/390829/sulteng-alokasikan-anggaran-rp103-miliar-untuk-pemerataan-internet","https://sultengprov.go.id/umum/diskominfosantik-sulteng-matangkan-berani-berdering-sinergi-jadi-kunci-sukses-internet-desa/"]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',10),
('official-content-2026-dinsos','Dinas Sosial Provinsi Sulawesi Tengah','In-Depth Interview (IDI) untuk pemutakhiran DTSEN','BERANI BERSINAR','Pemutakhiran Data Tunggal Sosial Ekonomi Nasional menggunakan wawancara mendalam untuk menggali akar masalah kemiskinan, kerentanan sosial, dan strategi bertahan hidup masyarakat miskin. Program terintegrasi melalui inovasi BERANI BERSINAR.','Melibatkan Dinsos Provinsi, Bappeda, Dinas PMD, Dukcapil, Inspektorat Provinsi, dan BPS. Dilaksanakan di Kota Palu, Kabupaten Donggala, Kabupaten Parigi Moutong, dan Kabupaten Morowali.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',20),
('official-content-2026-bappeda','Bappeda Provinsi Sulawesi Tengah','Pilot Project Fasilitator BERANI MOMBANGU','BERANI MOMBANGU','Program pemberdayaan masyarakat dan percepatan pengentasan kemiskinan serta penurunan stunting melalui penempatan tenaga fasilitator di desa/kelurahan.','50 fasilitator ditempatkan di 50 desa/kelurahan pada 5 kecamatan: Labuan, Tanantovea, Sindue, Banawa, dan Banawa Tengah.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',30),
('official-content-2026-perpus','Dinas Perpustakaan dan Kearsipan Daerah Provinsi Sulawesi Tengah','IPUSSULTENG dan transformasi layanan perpustakaan digital','IPUSSULTENG','Perpustakaan digital Sulawesi Tengah bekerja sama dengan IPUSNAS, disertai penguatan sistem kearsipan dan pengembangan layanan digital.','Dokumen mencatat peringkat kedua nasional perpustakaan digital selama dua tahun berturut-turut dan tingkat kegemaran membaca peringkat ke-7 nasional. Aplikasi arsip Souraja telah didaftarkan ke Kemendagri. Rencana berikutnya mencakup arsip aset berbasis barcode, aplikasi mandiri perpustakaan, dan program Bunda Literasi.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',40),
('official-content-2026-disbunak','Dinas Perkebunan dan Peternakan Provinsi Sulawesi Tengah','Peningkatan produktivitas perkebunan dan peternakan','Produktivitas & Hilirisasi','Program meliputi peningkatan produksi komoditas unggulan, benih unggul, pupuk, mekanisasi pertanian, inseminasi buatan, pelayanan kesehatan hewan, peningkatan kapasitas petani/peternak, serta hilirisasi kakao, kelapa, kopi, dan komoditas peternakan.','Program hilirisasi 2026 mencakup 29.950 hektare, 20.872.000 bibit, dan 1.914 kelompok tani. NTP perkebunan sampai Triwulan II 2026 sebesar 96,38 dan NTP peternakan 108,67. Dinas mengembangkan Sibunak, Berani Sampora, Si-Geper, serta pendataan bantuan berbasis NIK/nama/kelompok/lokasi/jumlah bantuan.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',50),
('official-content-2026-disperindag','Dinas Perindustrian dan Perdagangan Provinsi Sulawesi Tengah','Hilirisasi komoditas unggulan dan penguatan IKM','Hilirisasi & IKM','Fokus program meliputi hilirisasi komoditas kelapa, perikanan, dan durian, pembinaan industri/perdagangan, perlindungan konsumen, dan penguatan rantai pasok.','Kelapa dikembangkan menjadi tepung, konsentrat, nata de coco, dan produk turunan. Ekspor durian hingga Juni 2026 sekitar 7.000 ton. Fasilitasi HAKI dan sertifikasi halal ditargetkan mencapai 13.000 pelaku IKM. Dinas juga melakukan pengawasan LPG, operasi pasar murah, dan menjaga pasokan bahan pokok.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',60),
('official-content-2026-bpbd','Badan Penanggulangan Bencana Daerah (BPBD) Provinsi Sulawesi Tengah','SIGANA - Sistem Informasi Tanggap Bencana','SIGANA','Aplikasi memungkinkan masyarakat melaporkan kejadian bencana secara langsung dengan mengirim foto agar BPBD dapat merespons lebih cepat.','Data kebencanaan, termasuk contoh data banjir, terintegrasi dengan Command Center Pemerintah Provinsi Sulawesi Tengah. Dokumen sumber menyebut aplikasi tersedia di Play Store.','Siap Dibagikan','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',70),
('official-content-2026-pariwisata','Dinas Pariwisata Provinsi Sulawesi Tengah','Data program pariwisata',null,'Dokumen sumber mencantumkan Dinas Pariwisata sebagai kategori, tetapi tidak memuat rincian program pada versi dokumen yang diberikan.','Belum ada detail program yang dapat disajikan dari dokumen sumber.','Draft','[]'::jsonb,'INFORMASI & REFERENSI UNTUK PEMBUATAN KONTEN PROGRAM PEMPROV SULTENG 2026',80)
on conflict(source_key) do update set
opd_name=excluded.opd_name,title=excluded.title,program_label=excluded.program_label,detail=excluded.detail,key_facts=excluded.key_facts,status=excluded.status,reference_urls=excluded.reference_urls,source_label=excluded.source_label,sort_order=excluded.sort_order,updated_at=now();