
alter table public.berani_update_documents
  alter column file_path drop not null,
  add column if not exists document_kind text,
  add column if not exists display_title text,
  add column if not exists summary text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.berani_update_sections (
  id bigint generated by default as identity primary key,
  update_id bigint not null references public.berani_updates(id) on delete cascade,
  document_id bigint references public.berani_update_documents(id) on delete cascade,
  section_key text,
  title text not null,
  section_type text not null check (section_type in ('kpis','bar_chart','stat_grid','trend','facts','text','image')),
  payload jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists berani_update_sections_update_idx on public.berani_update_sections(update_id,sort_order,id);
create unique index if not exists berani_update_sections_key_uidx
  on public.berani_update_sections(update_id,section_key)
  where section_key is not null;

drop trigger if exists berani_update_sections_set_updated_at on public.berani_update_sections;
create trigger berani_update_sections_set_updated_at before update on public.berani_update_sections
for each row execute function public.set_updated_at();

alter table public.berani_update_sections enable row level security;
grant select,insert,update,delete on public.berani_update_sections to anon;
grant usage,select on all sequences in schema public to anon;

drop policy if exists public_read on public.berani_update_sections;
create policy public_read on public.berani_update_sections for select to anon using(true);
drop policy if exists public_insert on public.berani_update_sections;
create policy public_insert on public.berani_update_sections for insert to anon with check(true);
drop policy if exists public_update on public.berani_update_sections;
create policy public_update on public.berani_update_sections for update to anon using(true) with check(true);
drop policy if exists public_delete on public.berani_update_sections;
create policy public_delete on public.berani_update_sections for delete to anon using(true);

update storage.buckets
set file_size_limit=20971520,
    allowed_mime_types=array[
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
      'text/csv',
      'image/png',
      'image/jpeg',
      'image/webp'
    ]::text[]
where id='berani-documents';

drop policy if exists ah_berani_documents_insert on storage.objects;
create policy ah_berani_documents_insert
on storage.objects for insert to anon
with check (
  bucket_id='berani-documents'
  and lower(storage.extension(name)) in ('pdf','xlsx','xls','docx','doc','pptx','ppt','csv','png','jpg','jpeg','webp')
);

update storage.buckets
set file_size_limit=20971520,
    allowed_mime_types=array[
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
      'text/csv',
      'image/png',
      'image/jpeg',
      'image/webp'
    ]::text[]
where id='finding-documents';

drop policy if exists ah_finding_documents_insert on storage.objects;
create policy ah_finding_documents_insert on storage.objects for insert to anon
with check(
  bucket_id='finding-documents'
  and lower(storage.extension(name)) in ('pdf','xlsx','xls','docx','doc','pptx','ppt','csv','png','jpg','jpeg','webp')
);
