-- AH Center full-stack baseline schema.
-- Source of truth migrated from the legacy Google Apps Script + Google Sheets application.

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'viewer' check (role in ('admin','editor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kunjungan (
  id bigint generated by default as identity primary key,
  kode text generated always as ('KNJ-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  nama_opd text not null,
  tanggal date not null,
  pejabat text,
  anggota_tim text,
  topik text not null,
  status text not null default 'Terjadwal',
  link_notulen text,
  updated_at timestamptz not null default now()
);

create table if not exists public.isu_strategis (
  id bigint generated by default as identity primary key,
  kode text generated always as ('ISU-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  nama_isu text not null,
  opd_terkait text,
  prioritas text,
  ringkasan text,
  status_monitoring text not null default 'Monitoring',
  updated_at timestamptz not null default now()
);

create table if not exists public.rekomendasi (
  id bigint generated by default as identity primary key,
  kode text generated always as ('POL-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  judul text not null,
  opd_terkait text,
  ringkasan text,
  pic text,
  status text not null default 'Draft',
  link_doc text,
  updated_at timestamptz not null default now()
);

create table if not exists public.media_monitoring (
  id bigint generated by default as identity primary key,
  kode text generated always as ('MED-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  judul_berita text not null,
  nama_media text,
  tanggal date not null,
  sentimen text,
  link_berita text,
  updated_at timestamptz not null default now()
);

create table if not exists public.agenda (
  id bigint generated by default as identity primary key,
  kode text generated always as ('AGD-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  nama_agenda text not null,
  tanggal date not null,
  tipe text,
  status text not null default 'Terjadwal',
  pic text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tim_analisis (
  id bigint generated by default as identity primary key,
  kode text generated always as ('TIM-' || lpad(id::text, 4, '0')) stored unique,
  user_id uuid unique references auth.users(id) on delete set null,
  nama text not null,
  peran text,
  link_foto text,
  link_cv text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_agenda (
  id bigint generated by default as identity primary key,
  nama_agenda text not null unique,
  bobot numeric(10,2) not null default 1,
  kewajiban text not null default 'Peserta Dipilih' check (kewajiban in ('Semua Tim','Peserta Dipilih')),
  pengecualian text,
  status text not null default 'Aktif' check (status in ('Aktif','Nonaktif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_kontribusi (
  id bigint generated by default as identity primary key,
  nama_kontribusi text not null unique,
  bobot numeric(10,2) not null default 1,
  khusus_tim text,
  status text not null default 'Aktif' check (status in ('Aktif','Nonaktif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.absensi_agenda (
  id bigint generated by default as identity primary key,
  kode text generated always as ('ABSROW-' || lpad(id::text, 6, '0')) stored unique,
  agenda_event_id text not null,
  created_at timestamptz not null default now(),
  tanggal date not null,
  jenis_agenda text not null,
  detail_agenda text not null,
  lokasi text,
  tim_id bigint references public.tim_analisis(id) on delete restrict,
  nama_anggota text not null,
  status_kehadiran text not null check (status_kehadiran in ('Hadir','Izin','Tidak Hadir')),
  bobot_agenda numeric(10,2) not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.kontribusi_kerja (
  id bigint generated by default as identity primary key,
  kode text generated always as ('KTR-' || lpad(id::text, 4, '0')) stored unique,
  created_at timestamptz not null default now(),
  tanggal date not null,
  tim_id bigint references public.tim_analisis(id) on delete restrict,
  nama_anggota text not null,
  jenis_kontribusi text not null,
  keterangan text,
  status text not null default 'Dalam Proses',
  link_hasil text,
  bobot numeric(10,2) not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.pengaturan_kinerja (
  kunci text primary key,
  nilai numeric(14,2) not null,
  keterangan text,
  updated_at timestamptz not null default now()
);

create table if not exists public.finalisasi_honor (
  id bigint generated by default as identity primary key,
  kode text generated always as ('FINROW-' || lpad(id::text, 6, '0')) stored unique,
  finalization_id text not null,
  periode char(7) not null check (periode ~ '^\d{4}-\d{2}$'),
  finalized_at timestamptz not null default now(),
  status text not null default 'FINAL',
  tim_id bigint references public.tim_analisis(id) on delete restrict,
  nama_anggota text not null,
  peran text,
  required_agenda integer not null default 0,
  hadir integer not null default 0,
  izin integer not null default 0,
  tidak_hadir integer not null default 0,
  kehadiran_wajib_pct numeric(7,2) not null default 0,
  opd_excluded boolean not null default false,
  opd_required integer not null default 0,
  opd_hadir integer not null default 0,
  opd_pct numeric(7,2) not null default 0,
  rapat_required integer not null default 0,
  rapat_hadir integer not null default 0,
  rapat_pct numeric(7,2) not null default 0,
  total_kontribusi integer not null default 0,
  output_selesai integer not null default 0,
  poin_kontribusi numeric(12,2) not null default 0,
  basis_evaluasi text,
  nilai_evaluasi_pct numeric(7,2) not null default 0,
  rekomendasi_potongan numeric(14,2) not null default 0,
  honor_direkomendasikan numeric(14,2) not null default 0,
  label_rekomendasi text,
  catatan text,
  reopened_at timestamptz,
  reopened_reason text,
  unique (finalization_id, tim_id)
);

create index if not exists profiles_email_idx on public.profiles(lower(email));
create index if not exists kunjungan_tanggal_idx on public.kunjungan(tanggal desc);
create index if not exists kunjungan_status_idx on public.kunjungan(status);
create index if not exists isu_prioritas_status_idx on public.isu_strategis(prioritas, status_monitoring);
create index if not exists rekomendasi_status_idx on public.rekomendasi(status);
create index if not exists media_tanggal_idx on public.media_monitoring(tanggal desc);
create index if not exists agenda_tanggal_idx on public.agenda(tanggal desc);
create index if not exists absensi_agenda_event_idx on public.absensi_agenda(agenda_event_id);
create index if not exists absensi_tanggal_tim_idx on public.absensi_agenda(tanggal desc, tim_id);
create index if not exists absensi_agenda_tim_id_idx on public.absensi_agenda(tim_id);
create index if not exists kontribusi_tanggal_tim_idx on public.kontribusi_kerja(tanggal desc, tim_id);
create index if not exists kontribusi_kerja_tim_id_idx on public.kontribusi_kerja(tim_id);
create index if not exists finalisasi_honor_period_status_idx on public.finalisasi_honor(periode, status, finalized_at desc);
create index if not exists finalisasi_periode_idx on public.finalisasi_honor(periode, tim_id);
create index if not exists finalisasi_honor_tim_id_idx on public.finalisasi_honor(tim_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;
revoke execute on function public.set_updated_at() from public, anon, authenticated;

create sequence if not exists public.abs_event_seq start 1;
create or replace function public.next_attendance_event_id()
returns text language sql security invoker set search_path = '' as $$
  select 'ABS-' || lpad(nextval('public.abs_event_seq')::text, 4, '0');
$$;
revoke all on function public.next_attendance_event_id() from public, anon;
grant execute on function public.next_attendance_event_id() to authenticated;
grant usage, select on sequence public.abs_event_seq to authenticated;

create or replace function private.is_active_member()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles p where p.user_id = auth.uid() and p.active = true);
$$;
create or replace function private.has_role(allowed_roles text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles p where p.user_id = auth.uid() and p.active = true and p.role = any(allowed_roles));
$$;
revoke all on function private.is_active_member() from public, anon;
revoke all on function private.has_role(text[]) from public, anon;
grant execute on function private.is_active_member() to authenticated;
grant execute on function private.has_role(text[]) to authenticated;

do $$
declare t text;
begin
  foreach t in array array['profiles','kunjungan','isu_strategis','rekomendasi','media_monitoring','agenda','tim_analisis','master_agenda','master_kontribusi','absensi_agenda','kontribusi_kerja','pengaturan_kinerja'] loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', t || '_set_updated_at', t);
  end loop;
end $$;

insert into public.tim_analisis (nama, peran) values
('Muhammad Shadiq Muntashir','Fasilitator Pendidikan'),
('Muhammad Maruf','Tenaga Ahli DPRD Provinsi Sulteng'),
('Rizal Liara','Owner Bakul Sayur'),
('Moh. Yasin','SOI'),
('Fajri Ardiansyah','Fasilitator Desa'),
('Sri','Pendidik')
on conflict do nothing;

insert into public.master_agenda (nama_agenda,bobot,kewajiban,pengecualian,status) values
('Kunjungan OPD',5,'Semua Tim','Moh. Yasin','Aktif'),
('Rapat Internal',4,'Semua Tim',null,'Aktif'),
('Koordinasi Strategis',3,'Peserta Dipilih',null,'Aktif')
on conflict (nama_agenda) do nothing;

insert into public.master_kontribusi (nama_kontribusi,bobot,khusus_tim,status) values
('Menulis Esai',5,null,'Aktif'),('Talent Konten Opinimiu',4,null,'Aktif'),
('Menulis Naskah Carousel Opinimiu',4,null,'Aktif'),('Editing Video Opinimiu',4,null,'Aktif'),
('Editing Carousel Opinimiu',3,null,'Aktif'),('Menyusun Notulensi',2,null,'Aktif'),
('Produksi Konten daritengah.id',2,'Moh. Yasin','Aktif')
on conflict (nama_kontribusi) do nothing;

insert into public.pengaturan_kinerja (kunci,nilai,keterangan) values
('HONOR_DASAR',3500000,'Honorarium dasar per anggota per bulan'),
('POTONGAN_75_84',350000,'Rekomendasi potongan bila kehadiran wajib 75–84%'),
('POTONGAN_65_74',700000,'Rekomendasi potongan bila kehadiran wajib 65–74%'),
('POTONGAN_50_64',1050000,'Rekomendasi potongan bila kehadiran wajib 50–64%'),
('POTONGAN_35_49',1400000,'Rekomendasi potongan bila kehadiran wajib 35–49%'),
('POTONGAN_20_34',1750000,'Rekomendasi potongan bila kehadiran wajib 20–34%'),
('POTONGAN_0_19',2100000,'Rekomendasi potongan bila kehadiran wajib 0–19%'),
('FAKTOR_HADIR',1,'Nilai kehadiran penuh'),('FAKTOR_IZIN',0.5,'Izin resmi dihitung 50% bobot agenda'),
('FAKTOR_TIDAK_HADIR',0,'Tidak hadir/alpa tidak memperoleh bobot'),
('MIN_AGENDA_INTI_FLOOR',3,'Minimal jumlah OPD/rapat dalam sebulan sebelum agenda inti dapat menjadi dasar potongan terendah')
on conflict (kunci) do nothing;

create or replace view public.dashboard_stats with (security_invoker = true) as
select (select count(*) from public.kunjungan) total_kunjungan,
       (select count(*) from public.isu_strategis) total_isu,
       (select count(*) from public.rekomendasi) total_policy_brief,
       (select count(*) from public.media_monitoring) total_media,
       (select count(*) from public.agenda) total_agenda;

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant select on public.dashboard_stats to authenticated;

do $$
declare t text;
begin
  foreach t in array array['profiles','kunjungan','isu_strategis','rekomendasi','media_monitoring','agenda','tim_analisis','master_agenda','master_kontribusi','absensi_agenda','kontribusi_kerja','pengaturan_kinerja','finalisasi_honor'] loop
    execute format('alter table public.%I enable row level security',t);
  end loop;
end $$;

create policy profiles_select on public.profiles for select to authenticated using (user_id=auth.uid() or private.has_role(array['admin']));
create policy profiles_insert_admin on public.profiles for insert to authenticated with check (private.has_role(array['admin']));
create policy profiles_update_admin on public.profiles for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy profiles_delete_admin on public.profiles for delete to authenticated using (private.has_role(array['admin']));

do $$
declare t text;
begin
  foreach t in array array['kunjungan','isu_strategis','rekomendasi','media_monitoring','agenda','absensi_agenda','kontribusi_kerja','finalisasi_honor'] loop
    execute format('create policy %I on public.%I for select to authenticated using (private.is_active_member())',t||'_select_active',t);
    execute format('create policy %I on public.%I for insert to authenticated with check (private.has_role(array[''admin'',''editor'']))',t||'_insert_editor',t);
    execute format('create policy %I on public.%I for update to authenticated using (private.has_role(array[''admin'',''editor''])) with check (private.has_role(array[''admin'',''editor'']))',t||'_update_editor',t);
    execute format('create policy %I on public.%I for delete to authenticated using (private.has_role(array[''admin'',''editor'']))',t||'_delete_editor',t);
  end loop;
  foreach t in array array['tim_analisis','master_agenda','master_kontribusi','pengaturan_kinerja'] loop
    execute format('create policy %I on public.%I for select to authenticated using (private.is_active_member())',t||'_select_active',t);
    execute format('create policy %I on public.%I for insert to authenticated with check (private.has_role(array[''admin'']))',t||'_insert_admin',t);
    execute format('create policy %I on public.%I for update to authenticated using (private.has_role(array[''admin''])) with check (private.has_role(array[''admin'']))',t||'_update_admin',t);
    execute format('create policy %I on public.%I for delete to authenticated using (private.has_role(array[''admin'']))',t||'_delete_admin',t);
  end loop;
end $$;
